package database

import (
	"database/sql"
	"github.com/zabdiel-bknd/devtracker/internal/models"
)

// Service struct to handle database connection logic
type Service struct {

	db *sql.DB

}

// NewService is the "constructor" for our database layer.
func NewService(db *sql.DB) *Service {
	return &Service{db: db}
}

// CreateProject inserts a new project into the DB
func (s *Service) CreateProject(p *models.Project) error {
	query := `INSERT INTO projects (name, description, created_at) 
              VALUES ($1, $2, NOW()) RETURNING id, created_at`

	row := s.db.QueryRow(query, p.Name, p.Description)
	err := row.Scan(&p.ID, &p.CreatedAt) //if not error err will be nil

	return err
}

func (s *Service) GetProject(id int) (*models.Project, error){

	var project models.Project
	query := `SELECT id, name, description, created_at FROM projects WHERE id = $1`

	err := s.db.QueryRow(query, id).Scan(
		&project.ID,
		&project.Name,
		&project.Description,
		&project.CreatedAt,
	)

	if err != nil{
		return nil, err
	}

	return &project, nil
}

func (s *Service) CreateTask(task *models.Task) error{
	//Use RETURNING to get ID and timestamp generated by postgresql
	query := `
		INSERT INTO tasks (title, priority, status, project_id, created_at) 
		VALUES ($1, $2, $3, $4, NOW()) 
		RETURNING id, created_at
	`

	return s.db.QueryRow(
		query,
		task.Title,
		task.Priority,
		task.Status,
		task.ProjectID,
	).Scan(&task.ID, &task.CreatedAt) 
}

func (s *Service) GetTasksByProject(projectID int) ([]models.Task, error){
	query := `
		SELECT id, title, priority, status, created_at 
		FROM tasks 
		WHERE project_id = $1
		ORDER BY created_at DESC
	`

	rows, err := s.db.Query(query, projectID)
	if err != nil{
		return nil, err
	}

	// close the Rows iterator
	defer rows.Close()

	var tasks []models.Task

	for rows.Next(){
		var task models.Task

		err := rows.Scan(
			&task.ID,
			&task.Title,
			&task.Priority,
			&task.Status,
			&task.CreatedAt,
		)

		if err != nil{
			return nil, err
		}

		// not queried, but we have it as argument
		task.ProjectID =projectID
		tasks = append(tasks, task)

	}

	if err = rows.Err(); err != nil{
		return nil, err
	}

	return tasks, nil

}

func (s *Service) GetProjectsCount() (int, error) {
	var count int
	err := s.db.QueryRow("SELECT COUNT(*) FROM projects").Scan(&count)
	return count, err
}

func (s *Service) GetTasksCount() (int, error){
	var count int
	err := s.db.QueryRow("SELECT COUNT(*) FROM tasks").Scan(&count)
	return count, err
}

